### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bent0ws**
Ignore my previous commit, this is better.

### CODE REVIEW

**Comment by polyfractal** [comment]
Yep, good call. Thanks!

**Comment by bent0ws** [comment]
Hi Zachary, how are you?

Can you help me with a simplest information? I'm looking the documentation
of Elastic search ( I'm new here, previous I used Solr). I can't find a
full name into my index.

for example
$_GET[name] = "Zachary Tong";
$termQuery =
Sherlock::queryBuilder()->Term()->field("name")->term($_GET["name"]);

   $b = $request->index("jdbc")
            ->type("jdbc")
            ->from(0)
            ->to(110)
            ->query($termQuery);

it's return zero.. only return if I use the part of name.

Looking the documantation of elasticsearch, I founded this params:
http://www.elasticsearch.org/guide/reference/query-dsl/query-string-query/

but the one million question is: Where I can use it? Sherlock is ready to
use it?

Congratulations for yout job!!

regard,
Anderson Bento

2013/5/9 Zachary Tong notifications@github.com

**Comment by polyfractal** [comment]
Yep, query_string is in Sherlock:

``` php
$_GET[name] = "Zachary Tong"; 
$queryStringQuery = Sherlock::queryBuilder()->QueryString()
                                            ->query($_GET[name])
                                            ->default_field("name");

$b = $request->index("jdbc") 
              ->type("jdbc") 
              ->from(0) 
              ->to(110) 
              ->query($queryStringQuery); 
```

**Comment by bent0ws** [comment]
nice, works to me your example with this guy "->default_operator("AND");"

another question, are you know if can i storage a json data in a field and
query using fields of object json stored?

for example, a field called persons with this data:
[{"name":"Alan","id":"2"},{"name":"Daniel","id":"1"}]

and query for  persons->name

is possible?

I will pay a beer for us...lol

tks!!

2013/5/9 Zachary Tong notifications@github.com

**Comment by polyfractal** [comment]
Check out Elasticsearch's [Nested Documents](http://www.elasticsearch.org/guide/reference/mapping/nested-type/).  Unfortunately, Sherlock only has mediocre support for nested documents at the moment.  Some functions/methods are available while others are still missing.

**Comment by bent0ws** [comment]
Thanks Zachary :)

Are you need help in Sherlock?

2013/5/10 Zachary Tong notifications@github.com

**Pull request merged**
