### PR TITLE
unable to sort

### PR DESCRIPTION
**Pull request by chadkouse**
sherlock should allow you to specify a sort clause in your query.

### CODE REVIEW

**Comment by chadkouse** [comment]
I'm willing to try to tackle this if you want.  I was going to try to introduce the clause in the SearchRequest class.

**Comment by polyfractal** [comment]
Sure!  I won't have time to dig into it until tonight some time.

SearchRequest would be the right place, and it would function similar to the Type() or Index() methods.

**Comment by chadkouse** [comment]
See if how I did it makes sense with your framework.

**Comment by chadkouse** [comment]
oh yeah.. usage:

``` php
$sort =  new SortComponent();
$sort->field(array("medium_position"=>"asc"));
$sort->field(array("track_position"=>"asc"));
$request->sort($sort);
```

**Comment by chadkouse** [comment]
This is kinda ugly.... suggestions?

**Comment by polyfractal** [comment]
Started to merge your pull request, but realized the ES sort is actually a lot more complicated than I had imagined.  One thing turned into the next and I ended up replacing a lot of your code.  Sorry!  Looks like 0.90 added a lot more flexibility to the sorts.

Since my commit message got all garbled, here it is:

This refactors the pull request from chadkouse into a more comprehensive
package.  Turns out that ES allows fairly complicated/flexible sorting
(see http://www.elasticsearch.org/guide/reference/api/search/sort.html),
so an extendable builder-wrapper-component setup was needed.

Usage accepts an array of SortComponents:

``` php
$req->query($query);

$sort = Sherlock::sortBuilder();

$sortValues[] = $sort->Field()->name("sort1")->sort_order('asc');
$sortValues[] = $sort->Field()->name("sort2")->sort_order('desc');
$sortValues[] = $sort->Field()->name("_score");
$sortValues[] = $sort->Field()->name("sort3")->missing("_last");
$sortValues[] = $sort->Field()->name("sort3")->ignore_unmapped(true);

$req->sort($sortValues);
$response = $req->execute();
```

Individual SortComponents:

``` php
$req->sort(Sherlock::sortBuilder()->name("sort1")->sort_order('asc'));
```

Or as a sequence of parameters:

``` php
$sort1 = $sort->Field()->name("sort1")->sort_order('asc');
$sort2 = $sort->Field()->name("sort2")->sort_order('desc');

$req->sort($sort1, $sort2);
```

**Comment by chadkouse** [comment]
looks good thanks  

-- chad

**Comment by chadkouse** [comment]
What do you think about making it work more like this:

``` php
$req->query($query);
$sort = Sherlock::sortBuilder();
$sort->Field()->name("sort1")->sort_order('asc');
$sort->Field()->name("sort1")->sort_order('asc');
$req->sort($sort);
```

it looks cleaner and more intuitive to me but what do you think?  Is it doable and does it fit with your framework?

**Comment by polyfractal** [comment]
Long post inbound, mostly me thinking out loud.  Long story short: I'd _love_ for the syntax to look like that, it would be much cleaner.  I'm just not sure how to achieve it.  There are two problems currently.

The first problem is based on method chaining itself.  Each method inside the class naively returns $this, so the object doesn't really have any concept of "where" in the chain it is.  Each method is effectively an isolated property setter because of this.

The second main problem has to do with pollution of auto-complete/type hinting in IDEs.  Currently, the Sherlock::sortBuilder() method returns a SortWrapper, which contains the various Sorts (Field, Geo, etc).  Selecting one of these methods then returns the actual SortComponent that is associated.

This SortComponent contains type-hints specific to that component.  E.g. Geo sorts would contain geo-related, while the Field would not.

Basically, there are two levels type-hinting that need to be provided, otherwise everything get's lumped together into a big polluted namespace.

So getting back to syntax, this:

``` php
$sort->Field()->name("sort1")->sort_order('asc');
```

Operates entirely on the $sort object (each method returns $this, which refers to $sort).  That means the "method namespace" has to be filled with all potential methods, even if they don't apply to Field.

If Field() returns a different object (like a child SortComponent), the method chain is no longer operating on $sort and therefore doesn't save anything to the object.  This is the current setup, where the developer is required to store the sorts in a temporary variable.

We could potentially do something like this:

``` php
$sort->Field()->name("sort1")->sort_order('asc')->end();
```

And through some dependency injection or closure magic, the child SortComponent can signal to the parent SortWrapper that it is "finished" and should be added to the internal list of sorts.  The obvious disadvantage is that end() has to be called, and strange things will happen if it isn't.

Thoughts?  I'll do some more research this weekend and see if there is a clever way to fix this problem.  I agree that the syntax is much cleaner and simpler.

**Comment by polyfractal** [comment]
Actually, I have a halfway-not-terrible idea.  I'm integrating Symfony's EventDispatcher elsewhere in the code to encourage looser coupling between different moving parts.

Here is the idea, based on a dispatcher system:
- $sort is a SortWrapper like right now, returning a list of possible sort types (field, geo, etc)
- $sort->Field() would create a Field() object and injects an event listener callback into that new SortComponent.  
- Push the SortComponent onto an "active component" stack, return the new SortComponent.
- Each time the SortComponent is acted upon (e.g. ->name('abc')), the component dispatches an event to the $sort listener, which internally associates the event with the currently "active" component
- Continue this until a new SortComponent is requested ($sort->Geo), at which point finalize the old and repeat the whole process again.

Hmmm...I'll play with it and see if it works well.

**Pull request merged**
